### ISSUE TITLE
Share Video to Feed

### ISSUE THREAD

**Issue by roimulia** [Netwolf/ShareImageInstagram#1]
Is it possible to share video to feed?

**Comment by fabricioeus** [comment]
right now its only image to feed and stories, and video to stories. Video to feed i think its easier to do, do you need some help?

**Comment by roimulia** [comment]
Yes if possible. We are trying to share video to feed without the need to save it locally. Do you have a snippet on how to do it? (using UIDocumentController). For some reason sharing using UIActivityController doesn't work properly.. :\
