### ISSUE TITLE
Share video

### ISSUE THREAD

**Issue by ucelme** [Netwolf/ShareImageInstagram#4]
Hello. Is it possible to share videos to feed without saving them locally?

**Comment by fabricioeus** [comment]
> Hello. Is it possible to share videos to feed without saving them locally?

I think it is, I can try when a have a little more time. Is that ok? Feel free to fork and ask do a pull request as well

**Comment by ucelme** [comment]
Thank you. I tried to make it myself, but failed.

**Comment by ucelme** [comment]
Please, can you try to figure out if it's possible to share videos to feed without saving them locally?
